# This is a basic workflow to help you get started with Actions

name:  Synergy-linux

# Controls when the action will run. 
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
env:
  REPO_URL: https://github.com/symless/synergy-core.git

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        include:
#          - distro: debian9 #Need to install git 2.18+
          - distro: debian10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone source code
        run: |
          df -hT $PWD
          git clone $REPO_URL synergy-core

      - name: Build
        id: compile
        run: |
          pwd
          cd synergy-core
          mkdir build
          cd build
          pwd
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make -j
          echo "::set-output name=status::success"
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
         name: Synergy-linux-bin${{ env.FILE_DATE }}
         path: synergy-core/build/bin

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: Run unit test
        run: |
          ./synergy-core/build/bin/unittests
